export const locations = [
  'belfast',
  'northern-ireland',
  'ireland',
  'UK',
  'sydney',
  'sydney-cbd',
  'bondi',
  'coogee',
  'randwick',
  'maroubra',
  'bronte',
  'surry-hills',
  'darlinghurst',
  'paddington',
  'bondi-junction',
  'eastern-suburbs',
  'australia',
] as const 